# Generated by Django 2.0 on 2017-12-28 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('nbr_char_disp', models.IntegerField()),
                ('valeur', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Para_lu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texte', models.TextField()),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('notes', models.TextField()),
                ('para_lu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnage', to='principale.Para_lu')),
            ],
        ),
        migrations.CreateModel(
            name='Souscase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('nbr_char_disp', models.IntegerField()),
                ('valeur', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('personnage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur', to='principale.Personnage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='paragraphe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livre', to='principale.Paragraphe'),
        ),
        migrations.AddField(
            model_name='livre',
            name='personnage',
            field=models.ManyToManyField(related_name='livre', to='principale.Personnage'),
        ),
        migrations.AddField(
            model_name='case',
            name='souscase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='principale.Souscase'),
        ),
        migrations.AddField(
            model_name='bibliotheque',
            name='livre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotheque', to='principale.Livre'),
        ),
    ]
