# Generated by Django 2.0 on 2017-12-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0003_auto_20171230_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='titre',
            field=models.CharField(max_length=40),
        ),
    ]
