# Generated by Django 2.0 on 2017-12-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0004_auto_20171230_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnage',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
