# Generated by Django 2.0 on 2017-12-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0005_auto_20171230_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnage',
            name='notes',
            field=models.TextField(blank=True, default='test'),
            preserve_default=False,
        ),
    ]
