# Generated by Django 2.0 on 2018-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0007_choix_menu_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ordre',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
