# Generated by Django 2.0 on 2018-01-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0008_case_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['ordre', 'titre']},
        ),
    ]
