# Generated by Django 2.0 on 2018-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0009_auto_20180104_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeur_case',
            name='case',
        ),
        migrations.RemoveField(
            model_name='valeur_case',
            name='personnage',
        ),
    ]
