# Generated by Django 2.0 on 2018-01-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0010_auto_20180104_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur_case',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valeur_case', to='principale.Case'),
        ),
        migrations.AddField(
            model_name='valeur_case',
            name='personnage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valeur_case', to='principale.Personnage'),
        ),
    ]
