# Generated by Django 2.0 on 2018-01-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0011_auto_20180104_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnees_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('val_str', models.CharField(max_length=30, null=True)),
                ('val_int', models.IntegerField()),
            ],
        ),
    ]
