# Generated by Django 2.0 on 2018-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0014_auto_20180113_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees_site',
            name='explication',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donnees_site',
            name='val_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donnees_site',
            name='val_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
